<a href="https://colab.research.google.com/github/nosbyelk/hello-world/blob/master/Introdu%C3%A7%C3%A3o_ao_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao Numpy

In [ ]:
import numpy as np

Utilize a função range do python para criar automaticamente uma lista de números variando de 0 até 15.

In [ ]:
lista_automatica = list(range(0, 16))

print (lista_automatica)
print (type(lista_automatica))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
<class 'list'>


Converter a lista criada para um objeto do tipo numpy array.

In [ ]:
lista_automatica_numpy = np.asarray(lista_automatica)
print (lista_automatica_numpy)
print (type(lista_automatica_numpy))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>


Criar um novo array equivalente ao anterior utilizamndo diretamente os recursos do Numpy.

In [ ]:
array_com_numpy = np.arange(0,16)
print (array_com_numpy)
print (array_com_numpy.shape)
print (array_com_numpy.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
int64


Transformando inteiros em float

In [ ]:
array_com_numpy_float = array_com_numpy.astype(float)
print (array_com_numpy_float)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


Exemplo de matriz com mais de duas linhas.


In [ ]:
M = array_com_numpy_float.reshape(4, 4)
M


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
array_com_numpy_float.shape

(16,)

In [ ]:
elementos = M[0:2, 1:3]
elementos

array([[1., 2.],
       [5., 6.]])

Computar a média, mediana e o desvio padrão do array resultante da questão anterior.

In [ ]:
print ('Média:', np.mean(array_com_numpy_float))
print ('Mediana:', np.median(array_com_numpy_float))
print ('Desvio-padrão:', np.std(array_com_numpy_float))

Média: 7.5
Mediana: 7.5
Desvio-padrão: 4.6097722286464435


In [ ]:
M1 = M.copy()
M2 = M1 - np.max(M) - 1
print (M2)
print ('***************')
print (M2 * 2) 
print ('***************')
print (M2 * 2.3) 

[[-16. -15. -14. -13.]
 [-12. -11. -10.  -9.]
 [ -8.  -7.  -6.  -5.]
 [ -4.  -3.  -2.  -1.]]
***************
[[-32. -30. -28. -26.]
 [-24. -22. -20. -18.]
 [-16. -14. -12. -10.]
 [ -8.  -6.  -4.  -2.]]
***************
[[-36.8 -34.5 -32.2 -29.9]
 [-27.6 -25.3 -23.  -20.7]
 [-18.4 -16.1 -13.8 -11.5]
 [ -9.2  -6.9  -4.6  -2.3]]


Apresente uma contagem dos valores únicos que estão presentes no array criado na questão anterior. Siga o seguinte template: "Quantidade de ocorrências do elemento {}: {}"

In [ ]:
M2[1:3, 2:] = 10
M2

array([[-16., -15., -14., -13.],
       [-12., -11.,  10.,  10.],
       [ -8.,  -7.,  10.,  10.],
       [ -4.,  -3.,  -2.,  -1.]])

In [1]:
#Insira a resposta abaixo.
uniques, counts = np.unique(M2, return_counts=True)
print(uniques)
print(counts)

# [a, b ,c] [1, 2, 3]
# [(a,1), (b,2), (c,3)]

for u, c in zip (uniques, counts):
  print ('A quantidade de vezes que (...) foi {}: {}'.format (u,c))

NameError: ignored

# [Aula_Dia_11_Abril] Introdução ao Numpy

13 - Realize as seguintes operações:
Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4,2). Crie uma matriz identidade de dimensionalidade (4,4). Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentado o resultado final.

In [ ]:
M3 = np.full((4,2), 3)

MI = np.eye(4)

print(M3)
print("------")
print(np.transpose(M3))

M3T = np.transpose(M3)
M3MI = np.dot(M3T, MI)
print (M3MI)

[[3 3]
 [3 3]
 [3 3]
 [3 3]]
------
[[3 3 3 3]
 [3 3 3 3]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


14 - Realize as seguintes operações:
Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
Concatene horizontalmente as duas matrizes criadas anteriormente.

In [ ]:
M55 = np.arange(25,50).reshape(5, 5)
M51 = np.linspace(0, 1, 5).reshape(5,1)

print(M55)
print('_'*50)
print(M51)
print('_'*50)
MF = np.hstack((M55, M51))
print (MF)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
__________________________________________________
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
__________________________________________________
[[25.   26.   27.   28.   29.    0.  ]
 [30.   31.   32.   33.   34.    0.25]
 [35.   36.   37.   38.   39.    0.5 ]
 [40.   41.   42.   43.   44.    0.75]
 [45.   46.   47.   48.   49.    1.  ]]


In [ ]:
M17 = np.random.normal(size=36)

print(M17)
print('----------------')
print('Max', np.max(M17))
print('Min', np.min(M17))
print('Mean', np.mean(M17))
print('Std', np.std(M17))

[ 1.97532219  1.05272801 -0.86536479  0.40717196  0.0073714  -0.38473923
  0.64428107  0.0596361  -0.42349479 -1.70229831 -0.34665039  1.48913408
  0.20953594  0.70198371  0.34711288 -1.33810132 -1.23598482 -0.57308829
 -0.03354054  0.90006379  1.37543419 -0.69022643 -1.9653054   0.48196831
 -0.79777858 -2.38717326  0.57815863 -1.26046059  0.76726367  0.0761325
 -0.77350052 -1.39832228  0.96902481  1.2094179  -1.01613277  0.34889409]
----------------
Max 1.9753221905966014
Min -2.387173261645699
Mean -0.09976464161269043
Std 1.0285933469411581


18. Crie uma matriz de dimensões (50,50) com valores aleatórios entre 0 e 1 (distribuição uniforme). Exiba as duas últimas linhas da matriz.

In [ ]:
Q18 = np.random.rand(50,50)
print(Q18)
print('*'*50)
print(Q18[-2:])

[[0.73763552 0.46083478 0.63418797 ... 0.7540956  0.41865383 0.58557276]
 [0.17930548 0.47018083 0.10246374 ... 0.344308   0.32751821 0.32562094]
 [0.1499162  0.92344515 0.2358641  ... 0.1756365  0.48501583 0.5986453 ]
 ...
 [0.74755721 0.93359835 0.86348663 ... 0.85978947 0.21577733 0.40975277]
 [0.53810541 0.03327474 0.76154705 ... 0.56181429 0.47258241 0.13061697]
 [0.6126062  0.96302273 0.59355422 ... 0.12648478 0.44602944 0.3810087 ]]
**************************************************
[[0.53810541 0.03327474 0.76154705 0.03491616 0.83577784 0.19123049
  0.59060123 0.01012229 0.16792831 0.15926794 0.60425911 0.56250842
  0.96049275 0.25215197 0.23810379 0.70451908 0.55806854 0.89905215
  0.72817187 0.61338918 0.56283518 0.15883824 0.47388067 0.34264189
  0.3307393  0.09116621 0.03388824 0.56963705 0.29769959 0.91790463
  0.75616223 0.10638444 0.88764249 0.94456349 0.17478868 0.80907173
  0.08255975 0.07045446 0.73558542 0.11434383 0.49804572 0.38878888
  0.6857021  0.31212155 0.313

19. Utilize o array de números aleatórios anterior e apresente a soma de cada coluna. Em seguida, apresente a soma de cada linha.

In [ ]:
SC = np.sum(Q18, axis=0)
print('Col sum', SC)

SR = np.sum(Q18, axis=1)
print('Row sum', SR)

Col sum [25.79323248 25.00135778 23.98881881 24.13702258 22.59191612 27.27382739
 23.44830533 26.07874126 26.26798937 26.9182082  25.0181923  24.9013944
 25.04836042 26.75366913 23.07180564 25.63340573 23.70336515 28.08804966
 23.14811506 25.80762109 25.73894184 21.8184648  24.61374532 27.38279498
 22.67952172 25.81642663 20.37085131 22.69234953 21.30398149 27.70064958
 25.74023917 23.6881985  22.73629336 26.85962762 24.61769207 26.40585938
 26.55724234 22.6144969  25.61443321 26.27247884 25.83048205 21.55682786
 23.38897728 24.66465701 27.28678406 25.26966128 25.87087118 25.27786142
 24.70620278 23.43615129]
Row sum [23.76116886 22.86153016 20.67302118 25.34753381 25.25881053 24.79778221
 23.58746515 24.77357724 26.49527102 28.26019063 28.09709395 22.28419005
 26.29570365 20.65766161 24.32228905 19.78400653 25.97948009 23.7577517
 22.71610704 24.74514938 25.72870527 25.96788992 29.17306775 24.34705388
 25.77284641 25.81196801 27.41935037 24.96184098 21.63004213 23.0839647
 27.88968504

In [ ]:
M1 = np.full((5,5),1)
print(M1)

print('*-'*50)

M1[:2, :] = 0
M1[-2:,:] = 0
print(M1)

print('*-'*50)

print (np.sum(M1, axis=1))
print (np.sum(M1, axis=0)) 
print (np.sum(M1, axis=1))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
[0 0 5 0 0]
[1 1 1 1 1]


Crie dois arrays de 30 elementos contendo números aleatórios entre 1 a 3. Criar condição true false se estão no mesmo lugar.

In [ ]:
ra_a1 = np.random.randint(1, 4, 10)
ra_a2 = np.random.randint(1, 4, 10)

print (ra_a1)
print (ra_a2)

ra_a1_a2 = ra_a1 == ra_a2
print(ra_a1_a2)


[3 2 3 1 3 3 3 2 3 2]
[3 1 2 3 2 1 2 2 2 1]
[ True False False False False False False  True False False]


# Pandas

In [ ]:
pip install pandas

Introduzindo séries de dados do pandas
1. Importar as bibliotecas pandas e numpy com os aliases 'pd' e 'np', respectivamente.

In [ ]:
import numpy as np
import pandas as pd

Utilize o numpy para criar um array com 10 elementos de números inteiros aleatórios entre 50 e 100. Em seguida, transforme-o em uma série do pandas e a exiba.

In [ ]:
lista = np.random.randint(50, 100, 10)
print(lista)
serie = pd.Series(lista)
print(serie)

[56 79 96 58 78 90 68 69 91 65]
0    56
1    79
2    96
3    58
4    78
5    90
6    68
7    69
8    91
9    65
dtype: int64


In [ ]:
indeces = [elemento for elemento in list(range(20)) if elemento%2 !=0]
print(indeces)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [ ]:
series_2000 = pd.Series ([1,2,3], ['a', 'b', 'c'])
series_2000

a    1
b    2
c    3
dtype: int64

# [Aula_Dia_02_Maio] Introduzindo Dataframes


In [ ]:
import pandas as pd

Abaixo são definidos dois dicionários contendo capitais brasileiras com a população estimada para os anos de 2000 e 2018. Utilize ambos os dicionários definidos abaixos para criar dois objetos do tipo Series.

In [ ]:
populacao2000 = {'São Paulo': 10405867, 'Rio de Janeiro': 5851914, 'Salvador': 2440828, 'Belo Horizonte':2232747, 'Fortaleza':2138234	}
populacao2018 = {'São Paulo': 12176866, 'Rio de Janeiro': 6688927, 'Brasília': 2974703, 'Salvador': 2857329, 'Fortaleza': 2643247}

serie_2000 = pd.Series(list(populacao2000.values()), populacao2000.keys())
print('Ano 2000 \n',serie_2000)

serie_2018 = pd.Series(list(populacao2018.values()), populacao2018.keys())
print('Ano 2018 \n',serie_2018)

Ano 2000 
 São Paulo         10405867
Rio de Janeiro     5851914
Salvador           2440828
Belo Horizonte     2232747
Fortaleza          2138234
dtype: int64
Ano 2018 
 São Paulo         12176866
Rio de Janeiro     6688927
Brasília           2974703
Salvador           2857329
Fortaleza          2643247
dtype: int64


Crie uma nova série contendo a diferença entre as populações de 2018 e 2000.

In [ ]:
dif2018_2000 = (serie_2018 - serie_2000)
print(dif2018_2000)

Belo Horizonte          NaN
Brasília                NaN
Fortaleza          505013.0
Rio de Janeiro     837013.0
Salvador           416501.0
São Paulo         1770999.0
dtype: float64


Crie uma nova série contendo a média entre as duas séries iniciais.



In [ ]:
mean_dif = (serie_2018 - serie_2000)/2

print(mean_dif)

Belo Horizonte         NaN
Brasília               NaN
Fortaleza         252506.5
Rio de Janeiro    418506.5
Salvador          208250.5
São Paulo         885499.5
dtype: float64


In [ ]:
dic = {2000:serie_2000, 2018: serie_2018, 
       'diferenca':dif2018_2000, 'media':mean_dif}

df = pd.DataFrame(dic)

df

2000        2018  diferenca     media
Belo Horizonte   2232747.0         NaN        NaN       NaN
Brasília               NaN   2974703.0        NaN       NaN
Fortaleza        2138234.0   2643247.0   505013.0  252506.5
Rio de Janeiro   5851914.0   6688927.0   837013.0  418506.5
Salvador         2440828.0   2857329.0   416501.0  208250.5
São Paulo       10405867.0  12176866.0  1770999.0  885499.5

In [ ]:
data_frame_all = pd.concat([serie_2000, serie_2018, dif2018_2000, mean_dif], axis = 1, keys=dic.keys())
data_frame_all

2000        2018  diferenca     media
São Paulo       10405867.0  12176866.0  1770999.0  885499.5
Rio de Janeiro   5851914.0   6688927.0   837013.0  418506.5
Salvador         2440828.0   2857329.0   416501.0  208250.5
Belo Horizonte   2232747.0         NaN        NaN       NaN
Fortaleza        2138234.0   2643247.0   505013.0  252506.5
Brasília               NaN   2974703.0        NaN       NaN

Adicione uma nova coluna ao dataframe anterior chamada 2019, esta deve conter um acréscimo de 50000 sobre os valores da coluna 2018.

In [ ]:
data_frame_all[2019] = data_frame_all[2018] + 50000
data_frame_all


2000        2018  ...  (2019, 2021, 2020)  (2019, 2023)
São Paulo       10405867.0  12176866.0  ...                  99    12226866.0
Rio de Janeiro   5851914.0   6688927.0  ...                  99     6738927.0
Salvador         2440828.0   2857329.0  ...                  99     2907329.0
Belo Horizonte   2232747.0         NaN  ...                  99           NaN
Fortaleza        2138234.0   2643247.0  ...                  99     2693247.0
Brasília               NaN   2974703.0  ...                  99     3024703.0

[6 rows x 8 columns]

In [ ]:
data_frame_all.iloc[3][2019] = 50
data_frame_all

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


2000        2018  ...  (2019, 2021, 2020)  (2019, 2023)
São Paulo       10405867.0  12176866.0  ...                  99    12226866.0
Rio de Janeiro   5851914.0   6688927.0  ...                  99     6738927.0
Salvador         2440828.0   2857329.0  ...                  99     2907329.0
Belo Horizonte   2232747.0         NaN  ...                  99           NaN
Fortaleza        2138234.0   2643247.0  ...                  99     2693247.0
Brasília               NaN   2974703.0  ...                  99     3024703.0

[6 rows x 8 columns]

Exiba somente os dados referentes a Salvador.



In [ ]:
data_frame_all.loc['Salvador']

2000                  2440828.0
2018                  2857329.0
diferenca              416501.0
media                  208250.5
2019                  2907329.0
(2019, 2020)          2907329.0
(2019, 2021, 2020)         99.0
(2019, 2023)          2907329.0
Name: Salvador, dtype: float64

In [ ]:
data_frame_all.iloc[:3, :2]

2000        2018
São Paulo       10405867.0  12176866.0
Rio de Janeiro   5851914.0   6688927.0
Salvador         2440828.0   2857329.0

In [ ]:
data_frame_all[[2000, 2018]].loc[['Fortaleza', 'São Paulo', 'Salvador']]

2000        2018
Fortaleza   2138234.0   2643247.0
São Paulo  10405867.0  12176866.0
Salvador    2440828.0   2857329.0

In [ ]:
data_frame_all.drop(inplace=True)
data_frame_all

ValueError: ignored

# Exercícios com base de dados fictícia (toy dataset)


Execute o bloco de código abaixo para realizar o download de uma pequena base de dados que será utilizada para os próximos experimentos. A base de dados poderá ser acessada através do arquivo toy_dataset.csv. Caso a sessão se encerre, re-execute essa célula de código.

In [ ]:
!pip install -q kaggle
import os
os.environ['KAGGLE_USERNAME'] = "dayvidwelles"
os.environ['KAGGLE_KEY'] = "52be91b22529e7b4599d5fa9d96115cd"

!kaggle datasets download -d carlolepelaars/toy-dataset
!unzip toy-dataset.zip

  0% 0.00/1.13M [00:00<?, ?B/s]
100% 1.13M/1.13M [00:00<00:00, 78.5MB/s]
Archive:  toy-dataset.zip
  inflating: toy_dataset.csv         


Execute a leitura do Toy Dataset diretamente em um dataframe.



In [ ]:
df = pd.read_csv('/content/toy_dataset.csv')
df.head()

Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

Exiba o tipo de dados de cada coluna do dataframe.



In [ ]:
df.dtypes

Number       int64
City        object
Gender      object
Age          int64
Income     float64
Illness     object
dtype: object

18 - Realize as seguintes operações:

Adicione uma nova coluna chamada NumberAge e que apresente a soma entre os valores da coluna Number com os valores da coluna Age.
Exiba o cabeçalho do dataframe resultante.
Remova a coluna NumberAge.
Exiba o cabeçalho do dataframe resultante.

In [ ]:
df['NumberAge'] = df['Number'] + df['Age']
df.head()

Number    City Gender  Age   Income Illness  NumberAge
0       1  Dallas   Male   41  40367.0      No         42
1       2  Dallas   Male   54  45084.0      No         56
2       3  Dallas   Male   42  52483.0      No         45
3       4  Dallas   Male   40  40941.0      No         44
4       5  Dallas   Male   46  50289.0      No         51

In [ ]:
del df['NumberAge']
df.head()

Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

19 - Realize as seguintes operações a partir do dataframe definido anteriormente:

Exiba as cinco primeiras linhas do dataframe, todos os atributos devem ser apresentados com exceção do primeiro e último.

Exiba as cinco últimas linhas do dataframe, exiba somente o atributo City.

19 - Realize as seguintes operações a partir do dataframe definido anteriormente:

Exiba as cinco primeiras linhas do dataframe, todos os atributos devem ser apresentados com exceção do primeiro e último.

Exiba as cinco últimas linhas do dataframe, exiba somente o atributo City.

In [ ]:
df.iloc[:5, 1:5]

City Gender  Age   Income
0  Dallas   Male   41  40367.0
1  Dallas   Male   54  45084.0
2  Dallas   Male   42  52483.0
3  Dallas   Male   40  40941.0
4  Dallas   Male   46  50289.0

In [ ]:
np.unique(df.iloc[-5:, 1:2]['City'])[0]

'Austin'

In [ ]:
df.iloc[-5:, 1:2]['City'].iloc[1]

'Austin'

Ordene de forma ascendente as amostras de acordo utilizando como critério o salário anual. Em seguida, resete os índices dos registros.



In [ ]:
df.head()

Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [ ]:
df.sort_values('Income', inplace=True)

In [ ]:
df.head()

Number    City  Gender  Age  Income Illness
245       246  Dallas  Female   40  -654.0     Yes
7896     7897  Dallas  Female   34   584.0      No
18484   18485  Dallas  Female   43  2474.0      No
9298     9299  Dallas  Female   31  2667.0     Yes
17135   17136  Dallas  Female   39  3842.0      No

In [ ]:
df.reset_index(inplace=True, drop=True)

In [ ]:
df.head()

Number    City  Gender  Age  Income Illness
0     246  Dallas  Female   40  -654.0     Yes
1    7897  Dallas  Female   34   584.0      No
2   18485  Dallas  Female   43  2474.0      No
3    9299  Dallas  Female   31  2667.0     Yes
4   17136  Dallas  Female   39  3842.0      No

Início da aula do dia 9 de maio

In [ ]:
26 - Quantas pessoas tem um salário anual maior que R$ 30000?



In [ ]:
len(df[df['Income'] > 30000])

148218

Quantas pessoas estão doentes?



In [ ]:
len(df[df['Illness'] == 'Yes'])

In [ ]:
len(df[(df['Age'] == df['Age'].min()) & ((df['Income'] >= 40000) & (df['Income'] <= 42000))])

20

In [ ]:
df[(df['City'] == 'Austin') & (df['Age'] < 26)].head(5)

Number    City  Gender  Age   Income Illness
22736  149888  Austin  Female   25  66847.0      No
23073  144554  Austin    Male   25  67468.0      No
23489  147407  Austin  Female   25  68183.0      No
23560  146850  Austin  Female   25  68323.0      No
24295  149187  Austin  Female   25  69530.0      No

In [ ]:
df.describe()

Number            Age         Income
count  150000.000000  150000.000000  150000.000000
mean    75000.500000      44.950200   91252.798273
std     43301.414527      11.572486   24989.500948
min         1.000000      25.000000    -654.000000
25%     37500.750000      35.000000   80867.750000
50%     75000.500000      45.000000   93655.000000
75%    112500.250000      55.000000  104519.000000
max    150000.000000      65.000000  177157.000000

In [ ]:
df[df['Illness'] == 'Yes'][['City', 'Illness']].groupby('City').count()

Illness
City                    
Austin              1011
Boston               686
Dallas              1613
Los Angeles         2568
Mountain View       1178
New York City       4021
San Diego            394
Washington D.C.      668

Armazene em uma nova variável o agrupamento dos dados do dataframe usado anteriormente tomando como critério o gênero e a cidade, nessa exata ordem. Utilize a média como função de agregação e exiba somente a idade e salário anual.
